async(page)=>{
 const errors=[],failed=[],checks=[];try{
 page.on('pageerror',error=>errors.push(error.message));
 page.on('response',response=>{if(response.status()>=400&&response.url().startsWith('http://127.0.0.1:5173'))failed.push(response.url());});
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('http://127.0.0.1:5173/?project=customer-garden');
 const ready=()=>page.waitForFunction(()=>window.formaDebug?.().ready&&document.querySelector('#loading').hidden);
 await ready();
 const previousGeneric=await page.evaluate(()=>localStorage.getItem('forma-project'));
 await page.locator('#project-file').setInputFiles('../assets/customer-garden/Customer_Garden.forma.json');
 await page.waitForFunction(()=>window.formaDebug().state.instances.length===9);
 await page.getByRole('button',{name:'Ogród',exact:true}).click();
 await page.waitForTimeout(350);
 await page.screenshot({path:'test-results/customer-garden-desktop.png'});
 checks.push('Customer Garden loads its dedicated 27 x 48 m project');
 await page.getByRole('button',{name:'Cała działka',exact:true}).click();
 await page.waitForTimeout(300);
 await page.screenshot({path:'test-results/customer-garden-overview.png'});
 await page.getByRole('button',{name:'Z góry 2D',exact:true}).click();
 await page.waitForTimeout(300);
 await page.screenshot({path:'test-results/customer-garden-plan.png'});
 await page.getByRole('button',{name:'Widok z poziomu oczu',exact:true}).click();
 await page.waitForTimeout(300);
 await page.screenshot({path:'test-results/customer-garden-eye.png'});
 await page.getByRole('button',{name:'Ogród',exact:true}).click();
 checks.push('Garden, whole-plot, top-down and eye-level views');
 await page.getByRole('switch',{name:'Budynki',exact:true}).uncheck();
 await page.waitForFunction(()=>window.formaDebug().state.layers.buildings===false);
 await page.getByRole('switch',{name:'Budynki',exact:true}).check();
 checks.push('Fixed architecture visibility toggle');
 await page.getByRole('tab',{name:/Scena/}).click();
 await page.locator('[data-select="customer-sofa"]').click();
 await page.getByRole('button',{name:'Wycentruj widok',exact:true}).click();
 await page.waitForTimeout(500);
 const before=await page.evaluate(()=>window.formaDebug().state.instances.find(i=>i.id==='customer-sofa'));
 const screen=await page.evaluate(()=>window.formaDebug().objects.find(i=>i.id==='customer-sofa').screen);
 await page.mouse.move(screen[0],screen[1]);await page.mouse.down();await page.mouse.move(screen[0]+85,screen[1]+25,{steps:16});await page.mouse.up();
 await page.waitForTimeout(250);
 const moved=await page.evaluate(()=>window.formaDebug().state.instances.find(i=>i.id==='customer-sofa'));
 if(Math.hypot(moved.x-before.x,moved.z-before.z)<.1)throw Error('Direct drag did not move sofa');
 await page.getByRole('button',{name:'Cofnij',exact:true}).click();
 await page.waitForFunction(([x,z])=>{const i=window.formaDebug().state.instances.find(i=>i.id==='customer-sofa');return i.x===x&&i.z===z;},[before.x,before.z]);
 await page.getByRole('button',{name:'Ponów',exact:true}).click();
 await page.waitForFunction(([x,z])=>{const i=window.formaDebug().state.instances.find(i=>i.id==='customer-sofa');return i.x===x&&i.z===z;},[moved.x,moved.z]);
 checks.push('Direct ground drag, undo and redo');
 await page.getByRole('tab',{name:'Assets',exact:true}).click();
 await page.getByRole('button',{name:'Dodaj Nomad narożnik lewy',exact:true}).click();
 await page.waitForFunction(()=>window.formaDebug().state.instances.length===10&&document.querySelector('#loading').hidden);
 await page.getByRole('button',{name:'Usuń obiekt',exact:true}).click();
 await page.waitForFunction(()=>window.formaDebug().state.instances.length===9);
 checks.push('Add and remove a library asset');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Zapisz projekt',exact:true}).click();
 const download=await downloadPromise;await download.saveAs('test-results/customer-roundtrip.forma.json');
 await page.reload();await ready();
 const restored=await page.evaluate(()=>window.formaDebug().state.instances.find(i=>i.id==='customer-sofa'));
 if(restored.x!==moved.x||restored.z!==moved.z)throw Error('Customer layout did not persist');
 if(await page.evaluate(()=>localStorage.getItem('forma-project'))!==previousGeneric)throw Error('Previous generic project was modified');
 checks.push('Separate autosave and reload without changing the previous project');
 // Export the clean reference arrangement, not the temporary dragged test layout.
 await page.locator('#project-file').setInputFiles('../assets/customer-garden/Customer_Garden.forma.json');
 await page.waitForFunction(()=>window.formaDebug().state.instances.find(i=>i.id==='customer-sofa').x===-7.5);
 const glbPromise=page.waitForEvent('download',{timeout:90000});await page.getByRole('button',{name:'Eksportuj scenę GLB',exact:true}).click();
 const glb=await glbPromise;await glb.saveAs('../assets/customer-garden/Customer_Garden.glb');
 checks.push('Self-contained GLB scene export');
 await page.goto('http://127.0.0.1:5173/?project=customer-garden&webgl=1');await ready();
 if(await page.locator('#render-backend').innerText()!=='WebGL')throw Error('WebGL fallback failed');
 await page.screenshot({path:'test-results/customer-garden-webgl.png'});
 checks.push('WebGL fallback');
 const mobile=await page.context().browser().newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 mobile.on('pageerror',error=>errors.push(error.message));
 await mobile.goto('http://127.0.0.1:5173/?project=customer-garden');
 await mobile.waitForFunction(()=>window.formaDebug?.().ready&&document.querySelector('#loading').hidden);
 await mobile.waitForTimeout(500);await mobile.screenshot({path:'test-results/customer-garden-mobile.png'});
 if(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile horizontal overflow');
 await mobile.locator('#mobile-assets').click();
 const mobileInitial=await mobile.evaluate(()=>window.formaDebug().state.instances.length);
 await mobile.getByRole('button',{name:'Dodaj Stolik kawowy',exact:true}).click();
 await mobile.waitForFunction(n=>window.formaDebug().state.instances.length===n+1,mobileInitial);
 await mobile.getByRole('button',{name:'Wycentruj widok',exact:true}).click();
 await mobile.waitForTimeout(400);
 const mobileCanvas=await mobile.locator('canvas').screenshot();
 const colors=await mobile.evaluate(async data=>{const image=new Image();image.src='data:image/png;base64,'+data;await image.decode();const c=document.createElement('canvas');c.width=78;c.height=168;const ctx=c.getContext('2d');ctx.drawImage(image,0,0,78,168);const pixels=ctx.getImageData(0,0,78,168).data,result=new Set();for(let i=0;i<pixels.length;i+=4)result.add(`${pixels[i]>>3},${pixels[i+1]>>3},${pixels[i+2]>>3}`);return result.size;},mobileCanvas.toString('base64'));
 if(colors<25)throw Error('Blank mobile canvas');
 await mobile.locator('#mobile-properties').click();await mobile.screenshot({path:'test-results/customer-garden-mobile-properties.png'});
 await mobile.close();checks.push('390 px mobile rendering and asset editing');
 if(errors.length||failed.length)throw Error(JSON.stringify({errors,failed}));
 return {status:'PASS',checks,mobileColors:colors,drag:{before,after:moved},errors,failed};
}catch(error){throw Error(JSON.stringify({error:error.message,checks}));}
}
