import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const ready=()=>page.waitForFunction(()=>window.formaDebug?.().ready&&document.querySelector('#loading').hidden,null,{timeout:60000});
const debug=()=>page.evaluate(()=>window.formaDebug());
const change=async(key,value)=>{const input=page.locator(`[data-env-prop="${key}"]`);await input.fill(String(value));await input.press('Tab');};
try{
 await page.goto('http://127.0.0.1:5173/?project=customer-garden-premium&webgl');await ready();
 const original=await debug();assert.equal(original.environmentParts.length,12);
 await page.locator('#environment-edit').click();
 await page.locator('#toggle-library').click();
 const roomScreen=original.environmentParts.find(p=>p.id==='room').screen;
 await page.mouse.click(...roomScreen);
 assert.equal(await page.locator('#environment-part').inputValue(),'room');
 await page.locator('#toggle-library').click();
 await change('x',2);await change('z',1);await change('rotation',30);await change('scale',.9);
 let d=await debug();assert.deepEqual(d.state.environmentEdits.room,{x:2,z:1,rotation:30,scale:.9,visible:true});
 assert.notDeepEqual(d.environmentParts.find(p=>p.id==='room').position,original.environmentParts.find(p=>p.id==='room').position);
 await page.locator('#undo').click();assert.equal((await debug()).state.environmentEdits.room.scale,1);
 await page.locator('#redo').click();assert.equal((await debug()).state.environmentEdits.room.scale,.9);
 await page.screenshot({path:'test-results/environment-edit-desktop.png'});
 await page.reload();await ready();assert.equal((await debug()).state.environmentEdits.room.x,2);
 await page.locator('#environment-edit').click();await page.locator('#environment-part').selectOption('tank');
 await page.locator('[data-env-prop="visible"]').uncheck();assert.equal((await debug()).environmentParts.find(p=>p.id==='tank').visible,false);
 const downloadPromise=page.waitForEvent('download');await page.locator('#save-project').click();const download=await downloadPromise;const saved=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(saved.environmentEdits.room.x,2);assert.equal(saved.environmentEdits.tank.visible,false);
 await page.locator('#environment-reset').click();assert.equal((await debug()).environmentParts.find(p=>p.id==='tank').visible,true);
 await page.locator('#project-file').setInputFiles({name:'test.forma.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
 await page.waitForFunction(()=>window.formaDebug().state.environmentEdits.tank?.visible===false);
 const glbPromise=page.waitForEvent('download',{timeout:60000});await page.locator('#export-glb').click();const glb=await glbPromise;const bytes=await readFile(await glb.path());assert.equal(bytes.readUInt32LE(0),0x46546c67);const json=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());assert(json.nodes.some(n=>n.name==='Domek ogrodowy'));assert(!json.nodes.some(n=>n.name==='Zbiornik z oslona'));
 await page.setViewportSize({width:390,height:844});await page.locator('#environment-edit').click();await page.locator('#environment-edit').click();await page.locator('#environment-part').selectOption('patio');await change('x',.5);
 await page.screenshot({path:'test-results/environment-edit-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:1440,height:1000});await page.locator('#environment-edit').click();
 await page.getByRole('button',{name:'Ogród',exact:true}).click();await page.screenshot({path:'test-results/environment-edited-garden.png'});
 await page.goto('http://127.0.0.1:5173/?project=customer-garden');await ready();assert.deepEqual((await debug()).state.environmentEdits||{},{});
 assert.deepEqual(errors,[]);console.log('PASS: 12 parts, position/rotation/scale, undo/redo, persistence, visibility/reset, JSON roundtrip, mobile, original project isolation; no page errors.');
}finally{await browser.close();}
