import * as T from 'three/webgpu';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {createIcons,Pencil,Move,RotateCw,Maximize,RotateCcw,Scan,X} from 'lucide';
import {applyEnvironmentEdits,ENVIRONMENT_PARTS} from './environment-parts.js';
import './environment-editor.css';

export class EnvironmentEditor{
 constructor(engine,callbacks){
  this.engine=engine;this.cb=callbacks;this.selected=null;this.mode='translate';
  const button=document.createElement('button');button.id='environment-edit';button.className='button environment-edit-button';button.title='Environment Edit';button.setAttribute('aria-pressed','false');button.innerHTML='<i data-lucide="pencil"></i><span>Environment Edit</span>';document.querySelector('.project-heading').after(button);this.button=button;
  const panel=document.createElement('section');panel.id='environment-editor';panel.hidden=true;
  panel.innerHTML=`<div class="section-title"><span>Environment Edit</span><button id="environment-close" class="icon-button" title="Zakoncz edycje otoczenia" aria-label="Zakoncz edycje otoczenia"><i data-lucide="x"></i></button></div><label class="environment-label">Element<select id="environment-part"><option value="">Wybierz element</option></select></label><div id="environment-properties" hidden><div class="environment-modes">${[['translate','move','Przesun'],['rotate','rotate-cw','Obroc'],['scale','maximize','Skaluj']].map(([mode,icon,title])=>`<button class="icon-button" data-env-mode="${mode}" title="${title}" aria-label="${title} element otoczenia" aria-pressed="${mode==='translate'}"><i data-lucide="${icon}"></i></button>`).join('')}</div><div class="section-title">Przesuniecie <span>metry</span></div><div class="coordinate-fields">${['x','z'].map(axis=>`<label><span>${axis.toUpperCase()}</span><input type="number" data-env-prop="${axis}" aria-label="Environment ${axis.toUpperCase()}" min="-100" max="100" step="0.25"></label>`).join('')}</div><label class="property-row">Obrot <input type="number" data-env-prop="rotation" aria-label="Environment obrot" min="-360" max="360" step="15"></label><label class="property-row">Skala <input type="number" data-env-prop="scale" aria-label="Environment skala" min="0.25" max="3" step="0.1"></label><label class="property-row">Widoczny <input type="checkbox" data-env-prop="visible" aria-label="Environment widoczny"></label><div class="environment-actions"><button id="environment-focus" class="icon-button" title="Wycentruj element" aria-label="Wycentruj element otoczenia"><i data-lucide="scan"></i></button><button id="environment-reset" class="button subtle"><i data-lucide="rotate-ccw"></i>Przywroc element</button></div></div>`;
  document.querySelector('#inspector-body').before(panel);this.panel=panel;
  createIcons({icons:{Pencil,Move,RotateCw,Maximize,RotateCcw,Scan,X}});
  this.transform=new TransformControls(engine.camera,engine.renderer.domElement);this.transform.setSize(.85);this.transform.setSpace('local');engine.scene.add(this.transform.getHelper());
  this.transform.addEventListener('dragging-changed',e=>{engine.controls.enabled=!e.value;if(e.value)callbacks.before();else this.commit();});
  this.transform.addEventListener('objectChange',()=>{this.box?.update();this.fields(this.read());});
  button.onclick=()=>this.setActive(!engine.environmentEdit);
  panel.querySelector('#environment-close').onclick=()=>this.setActive(false);
  panel.querySelector('#environment-part').onchange=e=>this.select(e.target.value||null);
  panel.querySelector('#environment-reset').onclick=()=>{if(!this.selected)return;callbacks.before();const edits={...callbacks.get()};delete edits[this.selected];callbacks.set(edits);this.sync();};
  panel.querySelector('#environment-focus').onclick=()=>{const o=this.object();if(!o)return;const b=new T.Box3().setFromObject(o),c=b.getCenter(new T.Vector3()),d=Math.max(5,b.getSize(new T.Vector3()).length()*1.7);engine.controls.target.copy(c);engine.camera.position.copy(c).add(new T.Vector3(-.65,.75,-1).normalize().multiplyScalar(d));engine.controls.enableRotate=true;engine.controls.update();};
  panel.addEventListener('click',e=>{const b=e.target.closest('[data-env-mode]');if(b){this.mode=b.dataset.envMode;this.attach();}});
  panel.addEventListener('change',e=>{const key=e.target.dataset.envProp;if(!key||!this.selected)return;const v=key==='visible'?e.target.checked:Number(e.target.value);if(key!=='visible'&&(!Number.isFinite(v)||e.target.value===''))return this.sync();callbacks.before();const entry={...this.read(),[key]:key==='visible'?v:Math.min(Number(e.target.max),Math.max(Number(e.target.min),v))};callbacks.set({...callbacks.get(),[this.selected]:entry});this.sync();});
  engine.renderer.domElement.addEventListener('pointerdown',e=>{if(!engine.environmentEdit||e.button!==0||this.transform.axis)return;this.down=[e.clientX,e.clientY];},true);
  engine.renderer.domElement.addEventListener('pointerup',e=>{if(!engine.environmentEdit||!this.down||this.transform.dragging||this.transform.axis)return;const down=this.down;this.down=null;if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=engine.renderer.domElement.getBoundingClientRect();engine.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);engine.raycaster.setFromCamera(engine.pointer,engine.camera);const hits=engine.raycaster.intersectObjects([...engine.customer.parts.values()],true);for(const hit of hits){let o=hit.object,visible=true;while(o){if(!o.visible)visible=false;o=o.parent;}o=hit.object;while(o&&!o.userData.environmentId)o=o.parent;if(o&&visible){this.select(o.userData.environmentId);break;}}},true);
 }
 object(){return this.engine.customer?.parts.get(this.selected);}
 setActive(on){on=!!on&&!!this.engine.customer;this.engine.environmentEdit=on;this.button.setAttribute('aria-pressed',String(on));this.panel.hidden=!on;document.querySelector('#inspector-body').hidden=on;if(on){this.cb.deselect();document.querySelector('#inspector').classList.add('mobile-open');if(document.querySelector('#focus-workspace')?.getAttribute('aria-pressed')==='true')document.querySelector('#focus-workspace').click();if(document.querySelector('.workspace').classList.contains('hide-right')&&innerWidth>760)document.querySelector('#toggle-inspector').click();document.querySelector('#library-panel').classList.remove('mobile-open');}else{this.transform.detach();this.clearBox();}this.sync();}
 clearBox(){if(this.box){this.box.removeFromParent();this.box.geometry.dispose();this.box.material.dispose();this.box=null;}}
 select(id){this.selected=id;this.clearBox();const o=this.object();if(o&&o.visible){this.box=new T.BoxHelper(o,'#e7ce8d');this.engine.scene.add(this.box);}this.sync();}
 read(){const o=this.object();if(!o)return {};const b=o.userData.basePosition,s=this.engine.customer.root.scale;return {x:+((o.position.x-b[0])*s.x).toFixed(2),z:+((o.position.z-b[2])*s.z).toFixed(2),rotation:+T.MathUtils.radToDeg(o.rotation.y).toFixed(1),scale:+o.scale.x.toFixed(2),visible:o.visible};}
 commit(){if(!this.selected)return;const v=this.read();v.x=Math.max(-100,Math.min(100,v.x));v.z=Math.max(-100,Math.min(100,v.z));v.scale=Math.max(.25,Math.min(3,v.scale));v.rotation=((v.rotation%360)+360)%360;this.cb.set({...this.cb.get(),[this.selected]:v});this.sync();}
 fields(v){for(const input of this.panel.querySelectorAll('[data-env-prop]')){if(input.type==='checkbox')input.checked=v.visible!==false;else input.value=v[input.dataset.envProp]??(input.dataset.envProp==='scale'?1:0);}}
 attach(){this.transform.detach();const o=this.object();if(o&&o.visible&&this.engine.environmentEdit){this.transform.setMode(this.mode);this.transform.showX=this.mode!=='rotate';this.transform.showY=this.mode!=='translate';this.transform.showZ=this.mode!=='rotate';this.transform.setTranslationSnap(this.engine.snap?.25:null);this.transform.setRotationSnap(this.engine.snap?Math.PI/12:null);this.transform.attach(o);}for(const b of this.panel.querySelectorAll('[data-env-mode]'))b.setAttribute('aria-pressed',String(b.dataset.envMode===this.mode));}
 sync(){const e=this.engine;this.button.disabled=!e.customer;if(!e.customer&&e.environmentEdit)this.setActive(false);e.environmentEdits=this.cb.get();applyEnvironmentEdits(e.customer,e.environmentEdits);const select=this.panel.querySelector('#environment-part');const ids=[...(e.customer?.parts.keys()||[])];const signature=ids.join();if(this.signature!==signature){select.replaceChildren(new Option('Wybierz element',''),...ids.map(id=>new Option(ENVIRONMENT_PARTS[id],id)));this.signature=signature;}if(!ids.includes(this.selected))this.selected=null;select.value=this.selected||'';this.panel.querySelector('#environment-properties').hidden=!this.selected;this.fields(this.read());this.clearBox();if(this.object()?.visible&&e.environmentEdit){this.box=new T.BoxHelper(this.object(),'#e7ce8d');e.scene.add(this.box);}this.attach();for(const item of e.items.values())item.position.y=e.surfaceAt(item.position.x,item.position.z);}
}
