import './style.css';
import {EnvironmentEditor} from './environment-editor.js';
import {cleanEnvironmentEdits} from './environment-parts.js';
let environmentEditor;
import {premiumAssets} from './premium-furniture.js';
import './smart-concept.css';
import './workspace-panels.js';
import {mountCatalog} from './catalog-panel.js';
import {mountDaylight} from './daylight-panel.js';
import {cleanWeather,clockLabel} from './daylight.js';
let refreshDaylight=()=>{};
let cc0Catalog=[],refreshCatalog=()=>{};
import {customerProject,isCustomerProject,isPremiumProject,storageKey} from './customer-project.js';
import {createIcons,ArrowUpRight,Plus,Box,Layers,Search,Upload,ChevronDown,Move,RotateCw,Maximize,MousePointer2,Undo2,Redo2,Trash2,Copy,Scan,Grid2X2,Sun,Download,FolderOpen,X,Check,TreePine,Square,Compass,HelpCircle,PanelLeftClose,SlidersHorizontal,Image,Save,LoaderCircle} from 'lucide';
import {get,set} from 'idb-keyval';
const icons={ArrowUpRight,Plus,Box,Layers,Search,Upload,ChevronDown,Move,RotateCw,Maximize,MousePointer2,Undo2,Redo2,Trash2,Copy,Scan,Grid2X2,Sun,Download,FolderOpen,X,Check,TreePine,Square,Compass,HelpCircle,PanelLeftClose,SlidersHorizontal,Image,Save,LoaderCircle};
const icon=(name)=>`<i data-lucide="${name}"></i>`;
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const builtins=[
 ...premiumAssets,
 {id:'cube-plus',name:'Cube Plus',category:'Sauny i wellness',type:'SAUNA ZEWNĘTRZNA',dimensions:'5,0 × 2,5 × 2,6 m',url:'/models/cube-plus.glb',image:'/images/cube-plus.webp'},
 {id:'nomad-sofa',name:'Nomad Sofa',category:'Meble ogrodowe sofy',type:'SOFA MODUŁOWA',dimensions:'200 × 95 × 67 cm',note:'Wysokość siedziska: 35 cm',url:'/models/nomad-sofa.glb',image:'/images/nomad-sofa.webp'},
 {id:'nomad-chaise-left',name:'Nomad narożnik lewy',category:'Meble ogrodowe sofy',type:'SOFA Z SZEZLONGIEM',dimensions:'200 × ok. 140 × 67 cm',note:'Siedzisko: 35 cm. Głębokość szezlonga przybliżona ze zdjęcia.',url:'/models/nomad-chaise-left.glb',image:'/images/nomad-chaise-left.webp'},
 {id:'dining-table',name:'Stół ogrodowy',category:'Meble ogrodowe stoły',type:'STÓŁ OKRĄGŁY',dimensions:'Ø 116 × 76 cm',procedural:true,image:'/images/dining-table.webp'},
 {id:'garden-chair',name:'Krzesło ogrodowe',category:'Meble ogrodowe krzesła',type:'KRZESŁO',dimensions:'58 × 50 × 92 cm',procedural:true,image:'/images/garden-chair.webp'},
 {id:'coffee-table',name:'Stolik kawowy',category:'Meble ogrodowe stoły',type:'STOLIK',dimensions:'92 × 58 × 40 cm',procedural:true,image:'/images/coffee-table.webp'},
 {id:'planter',name:'Donica z zielenią',category:'Rośliny donice',type:'DONICA',dimensions:'Ø 50 × 85 cm',procedural:true,image:'/images/planter.webp'},
 {id:'bench',name:'Ławka ogrodowa',category:'Meble ogrodowe',type:'MEBLE OGRODOWE',dimensions:'1,8 × 0,6 × 0,9 m',url:'/models/bench.glb',image:'/images/bench.webp'}
];
let assets=[...builtins],selected=null,engine,busy=false,undo=[],redo=[],syncing=false,currentTab='assets',filter='all';
const legacyInitial={version:1,name:'Mój pierwszy ogród',environment:'garden',width:20,depth:16,time:14,grid:false,snap:true,instances:[{id:'cube-initial',assetId:'cube-plus',x:-1.4,z:-.9,rotation:0,scale:1}]};
const initial=isCustomerProject?customerProject:legacyInitial;
let state=structuredClone(initial);
try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved)state=validateState(saved);}catch{}
function validateState(s){if(s?.version!==1||!Array.isArray(s.instances)||s.instances.length>60)throw Error('Nieprawidłowy plik projektu.');const n=(v,min,max)=>{if(!Number.isFinite(v)||v<min||v>max)throw Error('Projekt zawiera nieprawidłowe wymiary.');return v;};const ids=new Set();return {version:1,environmentEdits:cleanEnvironmentEdits(s.environmentEdits),name:String(s.name||'Nowy ogród').slice(0,80),surfaces:Object.fromEntries(Object.entries(s.surfaces||{}).filter(([k,v])=>['patio','deck'].includes(k)&&typeof v==='string')),layers:{buildings:s.layers?.buildings!==false,planting:s.layers?.planting!==false,boundary:s.layers?.boundary!==false},environment:['customer','garden','studio','empty'].includes(s.environment)?s.environment:'garden',width:n(s.width,8,80),depth:n(s.depth,8,80),time:n(s.time,6,22),weather:cleanWeather(s.weather),landscapeVersion:s.landscapeVersion===1?1:0,grid:!!s.grid,snap:!!s.snap,instances:s.instances.map(i=>{if(typeof i.id!=='string'||ids.has(i.id)||typeof i.assetId!=='string')throw Error('Nieprawidłowe obiekty.');ids.add(i.id);return {id:i.id,assetId:i.assetId,x:n(i.x,-100,100),z:n(i.z,-100,100),rotation:n(i.rotation,-36000,36000),scale:n(i.scale,.1,10)};})};}
document.querySelector('#app').innerHTML=`
 <main class="workspace">
  <div id="viewport"></div>
  <header class="topbar glass">
   <a class="brand" href="?project=customer-garden" aria-label="Smart Concept Designer"><img src="/images/smart-concept-logo.png" alt="Smart Concept Ltd." width="220" height="58"><span class="brand-product">DESIGNER</span></a>
   <div class="project-heading"><select id="project-scene" class="project-selector" aria-label="Wybierz scenę"><option value="customer-garden-premium" ${isPremiumProject?'selected':''}>Customer Garden Premium</option><option value="customer-garden" ${isCustomerProject&&!isPremiumProject?'selected':''}>Customer Garden</option><option value="general" ${!isCustomerProject?'selected':''}>Mój ogród</option></select><input id="project-name" aria-label="Nazwa projektu" maxlength="80" value="${esc(state.name)}"><span id="saved-state" class="saved-state">Zapis lokalny</span></div>
   <div class="top-actions"><button class="button subtle open-project" title="Otwórz projekt">${icon('folder-open')}<span>Otwórz</span></button><button id="export-glb" class="icon-button" title="Eksportuj scenę GLB" aria-label="Eksportuj scenę GLB">${icon('box')}</button><button id="save-project" class="button primary">${icon('download')}<span>Zapisz projekt</span></button></div>
  </header>
  <aside id="library-panel" class="library glass panel">
   <div class="panel-heading"><span>Twoje narzędzia</span><button class="icon-button mobile-close" data-close="library" aria-label="Zamknij bibliotekę">${icon('x')}</button><span class="tiny-badge desktop-only">STUDIO / BETA</span></div>
   <div class="tabs" role="tablist" aria-label="Panel projektu"><button id="tab-assets" class="active" role="tab" aria-selected="true">${icon('box')}Assets</button><button id="tab-scene" role="tab" aria-selected="false">${icon('layers')}Scena <span id="scene-count">1</span></button></div>
   <section id="assets-content"><label class="search">${icon('search')}<input id="asset-search" placeholder="Znajdź obiekt…" aria-label="Szukaj assetów"><kbd>/</kbd></label>
    <div class="filter-row"><button data-filter="all" class="chip active">Wszystkie</button><button data-filter="cc0" class="chip">CC0</button><button data-filter="own" class="chip">Moje pliki</button></div>
    <div id="asset-list" class="asset-list"></div>
    <button id="import-asset" class="import-button">${icon('upload')}<span>Dodaj własny model<small>GLB · do 30 MB · tylko na urządzeniu</small></span>${icon('plus')}</button>
   </section>
   <section id="scene-content" hidden><p class="section-note">Obiekty w Twojej przestrzeni</p><div id="scene-list"></div></section>
   <section class="environment-section"><div class="section-title"><span>Środowisko</span><span class="muted">04</span></div><div class="environment-options"><button data-environment="customer" aria-label="Środowisko Customer Garden">${icon('compass')}<span>Customer Garden</span></button><button data-environment="garden" aria-label="Środowisko Ogród">${icon('tree-pine')}<span>Ogród</span></button><button data-environment="studio" aria-label="Środowisko Studio">${icon('box')}<span>Studio</span></button><button data-environment="empty" aria-label="Środowisko Pusta działka">${icon('square')}<span>Działka</span></button></div><div class="plot-fields"><label>Szerokość <span><input id="plot-width" type="number" min="8" max="80" step="1" aria-label="Szerokość działki">m</span></label><label>Długość <span><input id="plot-depth" type="number" min="8" max="80" step="1" aria-label="Długość działki">m</span></label></div></section>
   <div class="library-footer">Z pomysłu w przestrzeń.<span>01 / 3D</span></div>
  </aside>
  <div class="stage-heading"><span class="eyebrow">TWOJA PRZESTRZEŃ / 01</span><h1 id="scene-title">${isCustomerProject?'Customer Garden':'Koncepcja ogrodu'}</h1><p id="scene-subtitle">${isCustomerProject?'27 × 48 m · skala szacunkowa':'Dodaj obiekty i znajdź ich miejsce.'}</p></div>
  <div class="canvas-top"><div class="view-switch glass" role="group" aria-label="Widok kamery"><button id="view-3d" class="active">${isCustomerProject?'Ogród':'Perspektywa'}</button><button id="view-overview" class="customer-only">Cała działka</button><button id="view-top">Z góry <span>2D</span></button><button id="view-eye" class="customer-only" title="Widok z poziomu oczu" aria-label="Widok z poziomu oczu">${icon('mouse-pointer-2')}</button></div><button id="snapshot" class="icon-button glass" title="Zapisz obraz sceny" aria-label="Zapisz obraz sceny">${icon('image')}</button></div>
  <aside id="inspector" class="inspector glass panel"><div class="panel-heading"><span>Właściwości</span><button class="icon-button mobile-close" data-close="inspector" aria-label="Zamknij właściwości">${icon('x')}</button>${icon('sliders-horizontal')}</div><div id="inspector-body"></div><div class="customer-settings customer-only"><div class="toggle-row"><label for="layer-buildings">Budynki</label><input id="layer-buildings" data-layer="buildings" type="checkbox" role="switch" checked></div><div class="toggle-row"><label for="layer-planting">Nasadzenia</label><input id="layer-planting" data-layer="planting" type="checkbox" role="switch" checked></div><div class="toggle-row"><label for="layer-boundary">Ogrodzenie</label><input id="layer-boundary" data-layer="boundary" type="checkbox" role="switch" checked></div></div><div class="light-section"><div class="section-title"><span>${icon('sun')} Światło dzienne</span><output id="time-label">14:00</output></div><input type="range" id="sun-time" min="8" max="21" step="1" aria-label="Godzina światła"><div class="range-labels"><span>08:00</span><span>21:00</span></div></div><div class="toggle-row"><label for="show-grid">Siatka pomocnicza</label><input type="checkbox" id="show-grid" role="switch"></div><div class="toggle-row"><label for="snap">Przyciąganie · 25 cm</label><input type="checkbox" id="snap" role="switch"></div></aside>
  <div id="loading" class="loading glass" role="status"><span class="spinner"></span><div>Przygotowuję przestrzeń<small>Ładowanie modeli i materiałów…</small></div></div>
  <div class="tool-dock glass" role="toolbar" aria-label="Narzędzia edycji"><button class="icon-button active" data-mode="select" aria-label="Zaznacz" title="Zaznacz · Q">${icon('mouse-pointer-2')}</button><button class="icon-button" data-mode="translate" aria-label="Przesuń" title="Przesuń · W">${icon('move')}</button><button class="icon-button" data-mode="rotate" aria-label="Obróć" title="Obróć · E">${icon('rotate-cw')}</button><button class="icon-button" data-mode="scale" aria-label="Skaluj" title="Skaluj · R">${icon('maximize')}</button><span class="divider"></span><button id="undo" class="icon-button" aria-label="Cofnij" title="Cofnij · Ctrl Z" disabled>${icon('undo-2')}</button><button id="redo" class="icon-button" aria-label="Ponów" title="Ponów · Ctrl Shift Z" disabled>${icon('redo-2')}</button><span class="divider"></span><button id="focus" class="icon-button" aria-label="Wycentruj widok" title="Wycentruj · F">${icon('scan')}</button></div>
  <div class="compass glass" title="Orientacja sceny"><span>N</span>${icon('compass')}<small>1 jednostka = 1 m</small></div>
  <footer class="statusbar"><div><span class="live-dot"></span><span id="render-backend">Inicjalizacja 3D</span><span class="status-divider">/</span><span id="fps">— FPS</span><span class="status-divider">/</span><span id="object-status">1 obiekt</span></div><span class="navigation-hint">Przeciągnij, aby obrócić · Scroll, aby przybliżyć</span><button id="help" aria-label="Pomoc i skróty">${icon('help-circle')}<span>Pomoc</span></button></footer>
  <nav class="mobile-navigation glass"><button id="mobile-assets">${icon('box')}Assets</button><button id="mobile-properties">${icon('sliders-horizontal')}Właściwości</button></nav>
 </main><div id="toast" role="status" aria-live="polite"></div>
 <input type="file" id="asset-file" accept=".glb" hidden><input type="file" id="project-file" accept=".json" hidden>
 <dialog id="help-dialog" class="glass"><button class="icon-button dialog-close" aria-label="Zamknij pomoc">${icon('x')}</button><span class="eyebrow">TWOJE MAŁE STUDIO</span><h2>Przestrzeń pod kontrolą.</h2><p>Dodaj model z biblioteki. Kliknij go w scenie, a następnie wybierz narzędzie lub wpisz dokładne wartości we właściwościach.</p><dl><dt>Obracanie widoku</dt><dd>Przeciągnij / jeden palec</dd><dt>Przesuwanie widoku</dt><dd>Prawy przycisk / dwa palce</dd><dt>Przybliżanie</dt><dd>Scroll / gest szczypania</dd><dt>Zaznacz / Przesuń / Obróć / Skaluj</dt><dd>Q / W / E / R</dd><dt>Cofnij / Ponów</dt><dd>Ctrl Z / Ctrl Shift Z</dd><dt>Wycentruj / Usuń</dt><dd>F / Delete</dd></dl><p class="section-note">Projekt zapisuje się w tej przeglądarce. „Zapisz projekt” pobiera plik, który możesz później otworzyć — razem z użytymi własnymi modelami. Importowane pliki pozostają na Twoim urządzeniu.</p><button id="help-done" class="button primary">Zaczynam projektować ${icon('arrow-up-right')}</button></dialog>`;
function refreshIcons(){createIcons({icons,attrs:{'stroke-width':1.6}});}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(state));$('#saved-state').textContent='Zapisano na urządzeniu';}catch{$('#saved-state').textContent='Pobierz projekt, aby zapisać';}updateCounters();}
function checkpoint(){if(syncing)return;undo.push(JSON.stringify(state));if(undo.length>40)undo.shift();redo=[];historyButtons();}
function historyButtons(){$('#undo').disabled=!undo.length||busy;$('#redo').disabled=!redo.length||busy;}
function updateCounters(){$('#scene-count').textContent=state.instances.length;$('#object-status').textContent=`${state.instances.length} obiektów`;historyButtons();renderSceneList();}
function renderAssets(){const q=$('#asset-search').value.toLocaleLowerCase('pl');const list=assets.filter(a=>(filter!=='own'||a.custom)&&(filter!=='cc0'||a.license==='CC0-1.0')&&`${a.name} ${a.category}`.toLocaleLowerCase('pl').includes(q));$('#asset-list').innerHTML=list.length?list.map(a=>`<article class="asset-card"><div class="asset-image">${a.image?`<img src="${esc(a.image)}" alt="${esc(a.name)}" loading="lazy" width="640" height="440">`:`<div class="custom-preview">${icon('box')}</div>`}<span class="asset-type">${a.custom?'WŁASNY MODEL':a.license==='CC0-1.0'?'CC0':a.id==='cube-plus'?'PREMIUM':'KOLEKCJA'}</span><button class="add-asset" data-add="${esc(a.id)}" aria-label="Dodaj ${esc(a.name)}" ${busy?'disabled':''}>${icon('plus')}</button></div><div class="asset-info"><div><span class="asset-category">${esc(a.type||'WŁASNY MODEL')}</span><h3>${esc(a.name)}</h3></div><span class="asset-arrow">${icon('arrow-up-right')}</span><p>${esc(a.dimensions||'Wymiary z modelu')}</p>${a.source?`<a class="asset-source" href="${esc(a.source.url)}" target="_blank" rel="noopener">${esc(a.source.provider)} · CC0 · ${a.triangles.toLocaleString('pl')} trójkątów · ${(a.bytes/1048576).toFixed(1)} MB</a>`:''}</div></article>`).join(''):`<div class="empty-state">${icon('box')}<p>${filter==='own'?'Twoje modele pojawią się tutaj.':'Nie znaleziono obiektów.'}</p></div>`;refreshIcons();}
function renderSceneList(){$('#scene-list').innerHTML=state.instances.length?state.instances.map((i,n)=>`<button class="scene-row ${i.id===selected?'active':''}" data-select="${esc(i.id)}">${icon('box')}<span>${esc(assets.find(a=>a.id===i.assetId)?.name||'Model')}<small>Obiekt ${String(n+1).padStart(2,'0')}</small></span>${icon('scan')}</button>`).join(''):'<p class="section-note">Scena jest pusta. Dodaj pierwszy obiekt z biblioteki.</p>';refreshIcons();}
function renderInspector(){const i=state.instances.find(i=>i.id===selected),a=assets.find(a=>a.id===i?.assetId);$('#inspector-body').innerHTML=i?`<div class="selection-title"><span class="eyebrow">ZAZNACZONY OBIEKT</span><h2>${esc(a.name)}</h2><p>${esc(a.dimensions||'Własny model')}</p>${a.note?`<p>${esc(a.note)}</p>`:''}</div><div class="property-section"><div class="section-title">Pozycja <span class="muted">metry</span></div><div class="coordinate-fields"><label><span class="axis axis-x">X</span><input data-prop="x" aria-label="Pozycja X" type="number" min="-100" max="100" step="0.25" value="${i.x}"></label><label><span class="axis axis-z">Z</span><input data-prop="z" aria-label="Pozycja Z" type="number" min="-100" max="100" step="0.25" value="${i.z}"></label></div><label class="property-row"><span>Obrót</span><span><input data-prop="rotation" aria-label="Obrót w stopniach" type="number" step="15" value="${i.rotation}">°</span></label><label class="property-row"><span>Skala</span><span><input data-prop="scale" aria-label="Skala obiektu" type="number" min="0.1" max="10" step="0.1" value="${i.scale}">×</span></label></div><div class="selection-actions"><button id="duplicate" class="button subtle">${icon('copy')}Powiel</button><button id="delete" class="icon-button danger" aria-label="Usuń obiekt">${icon('trash-2')}</button></div>`:`<div class="empty-selection">${icon('mouse-pointer-2')}<h2>Wybierz obiekt</h2><p>Kliknij model w scenie, aby zmienić jego pozycję, obrót lub skalę.</p></div>`;refreshIcons();}
function select(id){if(id&&engine?.environmentEdit)environmentEditor?.setActive(false);selected=id;engine?.select(id);renderInspector();renderSceneList();}
function updateControls(){refreshDaylight();$('#project-name').value=state.name;$('#plot-width').value=state.width;$('#plot-depth').value=state.depth;$('#sun-time').value=state.time;$('#time-label').textContent=clockLabel(state.time);$('#show-grid').checked=state.grid;$('#snap').checked=state.snap;document.querySelectorAll('[data-environment]').forEach(b=>b.classList.toggle('active',b.dataset.environment===state.environment));const customer=state.environment==='customer';document.querySelectorAll('.customer-only').forEach(e=>e.hidden=!customer);$('#scene-title').textContent=customer?state.name:'Koncepcja ogrodu';$('#scene-subtitle').textContent=customer?`${state.width} × ${state.depth} m · skala szacunkowa`:'';$('#view-3d').textContent=customer?'Ogród':'Perspektywa';document.querySelectorAll('[data-layer]').forEach(input=>input.checked=state.layers?.[input.dataset.layer]!==false);if(engine?.ready){engine.setEnvironment(state.environment,state.width,state.depth);engine.setLighting(state.time,state.weather);engine.grid.visible=state.grid;engine.setSnap(state.snap);engine.setLayerVisibility(state.layers);environmentEditor?.sync();engine.surfaces.apply(engine.environment,state.surfaces,cc0Catalog).catch(e=>toast(e.message));refreshCatalog();}}
async function syncScene(){syncing=true;try{updateControls();for(const id of [...engine.items.keys()])if(!state.instances.some(i=>i.id===id))engine.remove(id);for(const i of state.instances){if(!engine.items.has(i.id)){const asset=assets.find(a=>a.id===i.assetId);if(!asset)throw Error('Brakuje modelu. Otwórz pełny plik projektu.');await engine.add(i,asset);}else engine.update(i);}updateControls();select(state.instances.some(i=>i.id===selected)?selected:null);persist();}finally{syncing=false;}}
async function addAsset(id){if(busy||!engine?.ready)return;if(state.instances.length>=60)return toast('Scena może zawierać maksymalnie 60 obiektów.');const a=assets.find(a=>a.id===id);if(!a)return;busy=true;renderAssets();$('#loading').hidden=false;try{await engine.loadAsset(a);const placement=await engine.findPlacement(a);checkpoint();const i={id:crypto.randomUUID(),assetId:id,x:placement.x,z:placement.z,rotation:0,scale:1};state.instances.push(i);await engine.add(i,a);select(i.id);persist();toast(`${a.name} dodano do sceny`);if(innerWidth<=760)$('#library-panel').classList.remove('mobile-open');}catch(e){toast(`Nie udało się wczytać modelu: ${e.message}`);}finally{busy=false;$('#loading').hidden=true;renderAssets();historyButtons();}}
function applyTransforms(list){for(const t of list){const i=state.instances.find(i=>i.id===t.id);if(i){i.x=Math.min(100,Math.max(-100,t.x));i.z=Math.min(100,Math.max(-100,t.z));i.rotation=t.rotation;i.scale=Math.min(10,Math.max(.1,t.scale));engine.update(i);}}renderInspector();persist();}
function removeSelected(){if(engine?.environmentEdit||!selected||busy)return;checkpoint();engine.remove(selected);state.instances=state.instances.filter(i=>i.id!==selected);select(null);persist();}
async function duplicate(){const original=state.instances.find(i=>i.id===selected);if(!original||busy)return;checkpoint();const i={...original,id:crypto.randomUUID(),x:original.x+.6,z:original.z+.6};state.instances.push(i);await engine.add(i,assets.find(a=>a.id===i.assetId));select(i.id);persist();}
async function travel(back){if(busy)return;const from=back?undo:redo,to=back?redo:undo;if(!from.length)return;busy=true;to.push(JSON.stringify(state));state=JSON.parse(from.pop());try{await syncScene();}catch(e){toast(e.message);}finally{busy=false;historyButtons();}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function encode(buffer){return new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.readAsDataURL(new Blob([buffer]));});}
function decode(b64){const s=atob(b64),bytes=new Uint8Array(s.length);for(let i=0;i<s.length;i++)bytes[i]=s.charCodeAt(i);return bytes.buffer;}
async function saveProject(){const custom=[];for(const a of assets.filter(a=>a.custom&&state.instances.some(i=>i.assetId===a.id)))custom.push({id:a.id,name:a.name,data:await encode(a.buffer)});download(new Blob([JSON.stringify({...state,customAssets:custom},null,2)],{type:'application/json'}),`${state.name.replace(/[^a-z0-9ąćęłńóśźż -]/gi,'').slice(0,60)||'projekt'}.forma.json`);toast('Projekt pobrany — możesz go później otworzyć.');}
function verifyGLB(buffer){const view=new DataView(buffer);if(buffer.byteLength<20||view.getUint32(0,true)!==0x46546c67||view.getUint32(4,true)!==2)throw Error('Wybierz poprawny plik GLB 2.0.');const len=view.getUint32(12,true);const json=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,20,len)));if([...(json.images||[]),...(json.buffers||[])].some(x=>x.uri&&!x.uri.startsWith('data:')))throw Error('GLB musi zawierać tekstury wewnątrz pliku.');}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.add)await addAsset(b.dataset.add);if(b.dataset.select)select(b.dataset.select);if(b.dataset.mode){if(engine?.environmentEdit&&b.dataset.mode!=='select'){environmentEditor.mode=b.dataset.mode;environmentEditor.attach();}engine?.setMode(b.dataset.mode);document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));}if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderAssets();}if(b.dataset.environment&&!busy){checkpoint();state.environment=b.dataset.environment;updateControls();persist();}if(b.dataset.close)$('#'+(b.dataset.close==='library'?'library-panel':'inspector')).classList.remove('mobile-open');if(b.id==='duplicate')await duplicate();if(b.id==='delete')removeSelected();});
$('#asset-search').addEventListener('input',renderAssets);
$('#project-scene').onchange=e=>{persist();location.href=e.target.value==='general'?'/':'/?project='+encodeURIComponent(e.target.value);};
for(const input of document.querySelectorAll('[data-layer]'))input.onchange=()=>{checkpoint();state.layers={...state.layers,[input.dataset.layer]:input.checked};engine.setLayerVisibility(state.layers);persist();};
$('#view-overview').onclick=()=>{engine?.cameraView('overview');document.querySelectorAll('.view-switch button').forEach(b=>b.classList.toggle('active',b.id==='view-overview'));};
$('#view-eye').onclick=()=>{engine?.cameraView('eye');document.querySelectorAll('.view-switch button').forEach(b=>b.classList.toggle('active',b.id==='view-eye'));};
$('#export-glb').onclick=async()=>{if(busy||!engine?.ready)return;busy=true;$('#export-glb').disabled=true;try{const data=await engine.exportScene();download(new Blob([data],{type:'model/gltf-binary'}),'Customer-Garden.glb');toast('Scena GLB została pobrana.');}catch(e){toast(`Eksport nie powiódł się: ${e.message}`);}finally{busy=false;$('#export-glb').disabled=false;}};
for(const tab of ['assets','scene'])$('#tab-'+tab).addEventListener('click',()=>{currentTab=tab;for(const t of ['assets','scene']){$('#tab-'+t).classList.toggle('active',t===tab);$('#tab-'+t).setAttribute('aria-selected',String(t===tab));$('#'+t+'-content').hidden=t!==tab;}});
$('#project-name').addEventListener('change',e=>{checkpoint();state.name=e.target.value.trim()||'Nowy ogród';e.target.value=state.name;persist();});
$('#inspector-body').addEventListener('change',e=>{const key=e.target.dataset.prop,i=state.instances.find(i=>i.id===selected);if(!key||!i)return;const v=Number(e.target.value);if(!Number.isFinite(v)||e.target.value==='')return renderInspector();checkpoint();i[key]=key==='scale'?Math.min(10,Math.max(.1,v)):key==='rotation'?v%360:Math.min(100,Math.max(-100,v));engine.update(i);renderInspector();persist();});
for(const [id,key] of [['plot-width','width'],['plot-depth','depth']])$('#'+id).addEventListener('change',e=>{checkpoint();state[key]=Math.max(8,Math.min(80,Number(e.target.value)||20));updateControls();persist();});
let weatherEditAt=0;
refreshDaylight=mountDaylight({get:()=>state,set:(key,value)=>{if(performance.now()-weatherEditAt>500)checkpoint();weatherEditAt=performance.now();state.weather={...cleanWeather(state.weather),[key]:value};engine?.setLighting(state.time,state.weather);persist();}});
$('#sun-time').addEventListener('pointerdown',checkpoint);$('#sun-time').addEventListener('keydown',e=>{if(e.key.startsWith('Arrow'))checkpoint();});$('#sun-time').addEventListener('input',e=>{state.time=Number(e.target.value);$('#time-label').textContent=clockLabel(state.time);refreshDaylight();engine?.setLighting(state.time,state.weather);persist();});
$('#show-grid').addEventListener('change',e=>{checkpoint();state.grid=e.target.checked;engine.grid.visible=state.grid;persist();});$('#snap').addEventListener('change',e=>{checkpoint();state.snap=e.target.checked;engine.setSnap(state.snap);persist();});
$('#view-3d').onclick=()=>{engine?.cameraView('perspective');document.querySelectorAll('.view-switch button').forEach(b=>b.classList.toggle('active',b.id==='view-3d'));};$('#view-top').onclick=()=>{engine?.cameraView('top');document.querySelectorAll('.view-switch button').forEach(b=>b.classList.toggle('active',b.id==='view-top'));};$('#focus').onclick=()=>engine?.focus();$('#undo').onclick=()=>travel(true);$('#redo').onclick=()=>travel(false);$('#save-project').onclick=saveProject;
$('#snapshot').onclick=()=>{try{const a=document.createElement('a');a.href=engine.screenshot();a.download='forma-wizualizacja.png';a.click();toast('Zapisano obraz sceny 3D.');}catch{toast('Nie udało się zapisać obrazu. Spróbuj ponownie.');}};
$('#import-asset').onclick=()=>$('#asset-file').click();$('.open-project').onclick=()=>$('#project-file').click();
$('#asset-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>30*1024*1024)return toast('Maksymalny rozmiar modelu to 30 MB.');try{const buffer=await file.arrayBuffer();verifyGLB(buffer);const asset={id:'custom-'+crypto.randomUUID(),name:file.name.replace(/\.glb$/i,'').slice(0,60),category:'Moje modele',custom:true,buffer};await engine.loadAsset(asset);assets.push(asset);await set('forma-assets',assets.filter(a=>a.custom));filter='own';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));renderAssets();toast('Model jest w bibliotece. Kliknij +, aby dodać go do sceny.');}catch(err){toast(err.message||'Nie można zaimportować modelu.');}};
$('#project-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>70*1024*1024)return toast('Plik projektu jest zbyt duży (maks. 70 MB).');try{const json=JSON.parse(await file.text()),next=validateState(json);next.landscapeVersion=1;const staged=[];for(const a of json.customAssets||[]){if(typeof a.id!=='string'||typeof a.data!=='string'||a.data.length>42*1024*1024)throw Error('Nieprawidłowy model w projekcie.');const buffer=decode(a.data);verifyGLB(buffer);staged.push({id:a.id,name:String(a.name).slice(0,60),custom:true,category:'Moje modele',buffer});}const available=[...builtins,...assets.filter(a=>a.custom),...staged];for(const i of next.instances){const a=available.find(a=>a.id===i.assetId);if(!a)throw Error('W pliku brakuje modelu użytego w projekcie.');await engine.loadAsset(a);}checkpoint();for(const a of staged)if(!assets.some(x=>x.id===a.id))assets.push(a);await set('forma-assets',assets.filter(a=>a.custom));state=next;await syncScene();renderAssets();toast('Projekt został otwarty.');}catch(err){toast(err.message||'Nie udało się otworzyć projektu.');}};
$('#mobile-assets').onclick=()=>{$('#library-panel').classList.toggle('mobile-open');$('#inspector').classList.remove('mobile-open');};$('#mobile-properties').onclick=()=>{$('#inspector').classList.toggle('mobile-open');$('#library-panel').classList.remove('mobile-open');};
$('#help').onclick=()=>$('#help-dialog').showModal();$('.dialog-close').onclick=$('#help-done').onclick=()=>$('#help-dialog').close();
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('#help-dialog').open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();travel(!e.shiftKey);return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject();return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeSelected();}if(e.key.toLowerCase()==='f')engine?.focus();if(e.key==='/'){e.preventDefault();$('#asset-search').focus();}const m={q:'select',w:'translate',e:'rotate',r:'scale'}[e.key.toLowerCase()];if(m)document.querySelector(`[data-mode="${m}"]`).click();});
renderAssets();renderInspector();updateControls();refreshIcons();
async function start(){try{
 try{const response=await fetch('/assets.json');if(!response.ok)throw Error('Katalog CC0 jest niedostępny');cc0Catalog=(await response.json()).assets;assets.push(...cc0Catalog.filter(a=>a.kind==='model').map(a=>({...a,url:a.path,image:a.preview,type:a.category,dimensions:`${a.dimensions.width} × ${a.dimensions.depth} × ${a.dimensions.height} m`})));
 refreshCatalog=mountCatalog(cc0Catalog,{current:()=>state.surfaces,environment:()=>state.environment,apply:async(target,id)=>{if(busy||!engine?.ready)return;busy=true;try{const next={...state.surfaces};if(id)next[target]=id;else delete next[target];await engine.surfaces.apply(engine.environment,next,cc0Catalog);checkpoint();state.surfaces=next;persist();toast('Materiał został zmieniony.');}catch(e){toast(e.message);}finally{busy=false;}}});
 }catch(e){toast(e.message);}
 try{const stored=await get('forma-assets');if(Array.isArray(stored))assets.push(...stored);}catch{toast('Własne modele nie będą zapisywane w tej przeglądarce.');}const {GardenScene}=await import('./scene.js');engine=new GardenScene($('#viewport'),{select,beforeChange:checkpoint,changed:applyTransforms,live:list=>{const t=list.find(i=>i.id===selected);if(t)for(const key of ['x','z','rotation','scale']){const input=document.querySelector(`[data-prop="${key}"]`);if(input&&document.activeElement!==input)input.value=t[key];}},renderer:name=>$('#render-backend').textContent=name,fps:value=>$('#fps').textContent=`${value} FPS`});await engine.init();environmentEditor=new EnvironmentEditor(engine,{get:()=>state.environmentEdits||{},before:checkpoint,set:edits=>{state.environmentEdits=cleanEnvironmentEdits(edits);persist();},deselect:()=>select(null)});
if(isCustomerProject&&state.environment==='customer'){
 const moves=[[-3,-7.3,-2.1,-8.9],[2.4,-9.85,1.9,-10.4],[4.1,-10.25,.2,-10.1],[3.5,-10.2,.7,-10.1]];
 for(const item of state.instances)if(item.id.startsWith('realism-'))for(const [x,z,nx,nz] of moves)if(Math.abs(item.x-x*state.width/15)<.01&&Math.abs(item.z-z*state.depth/25)<.01){item.x=nx*state.width/15;item.z=nz*state.depth/25;}
}
if(isCustomerProject&&state.environment==='customer'&&!state.landscapeVersion&&assets.some(a=>a.id==='ph-fern_02')){
 state.landscapeVersion=1;
 checkpoint();
 const planting=[[-4.7,-4.4],[-4.15,-6.05],[-2.1,-8.9],[1.1,-9.6],[1.9,-10.4],[.2,-10.1]];
 for(const [index,[x,z]] of planting.entries())if(state.instances.length<60)state.instances.push({id:'realism-fern-'+crypto.randomUUID(),assetId:'ph-fern_02',x:x*state.width/15,z:z*state.depth/25,rotation:index*57,scale:.65});
 for(const [x,z] of [[-4.5,-5.2],[1.6,-9.8],[.7,-10.1]])if(state.instances.length<60)state.instances.push({id:'realism-rock-'+crypto.randomUUID(),assetId:'ph-rock_07',x:x*state.width/15,z:z*state.depth/25,rotation:35,scale:2});
 state.landscapeVersion=1;
}
await syncScene();select(isCustomerProject?null:state.instances[0]?.id??null);$('#loading').hidden=true;renderAssets();document.body.classList.add('ready');registerTools();}catch(e){console.error(e);$('#loading').innerHTML=`<div><strong>Nie udało się uruchomić sceny</strong><small>${esc(e.message)}. Odśwież stronę lub włącz akcelerację sprzętową w przeglądarce.</small><button class="button" onclick="location.reload()">Spróbuj ponownie</button></div>`;}}
function registerTools(){if(!document.modelContext?.registerTool)return;const tools=[{name:'read_garden_project',description:'Read current garden layout and available assets.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({project:structuredClone(state),assets:assets.map(({id,name})=>({id,name}))})},{name:'add_garden_asset',description:'Add a library asset to the current garden scene.',inputSchema:{type:'object',properties:{assetId:{type:'string'}},required:['assetId'],additionalProperties:false},execute:async input=>{if(typeof input?.assetId!=='string'||!assets.some(a=>a.id===input.assetId))throw Error('Unknown asset');await addAsset(input.assetId);return {objects:state.instances.length};}}];for(const t of tools)try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{});}catch{}}
// Read-only diagnostics used by local acceptance checks.
window.formaDebug=()=>({...engine?.diagnostics(),ready:!!engine?.ready,backend:$('#render-backend').textContent,state:structuredClone(state),selected,assets:assets.map(a=>({id:a.id,name:a.name})),drawCalls:engine?.renderStats?.calls,triangles:engine?.renderStats?.triangles});
start();
